using System;
using UnityEngine;

namespace InterfaceOff
{
    public abstract class WindowBase : MonoBehaviour
    {
        public WindowInteractions Interactions { get; set; }
        public WindowComponents Components { get; set; }
        
        public void InstantiateWindowBase()
        {
            transform.position = CanvasManager.GetRandomPositionOnCanvas();
            
            OnWindowInstantiation();
        }

        public virtual void OnWindowInstantiation() { }
        public virtual void OnWindowClicked() { }
    }
}
